name: prism_connect
description: Library for connecting and sending commands to PRISM Live Studio's remote control protocol
version: 1.0.0
homepage: https://github.com/entriphy/prism_connect
repository: https://github.com/entriphy/prism_connect

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
